// Kidai Clipboard (纪代剪贴板) — host half.
//
// The host half is a storage owner only: it exposes a tiny JSON API over the
// `webServer` service and persists the clipboard state to
// `$DSH_HOME/kidai-clipboard/store.json` with atomic writes. All behavior
// (floating window, capture, fork, folders, tags) lives in lib/client.js,
// which the client-modules node half serves to the browser.
//
// Mirrors the shape of dsh-whale-widget: routes are registered through
// ctx.webServer.register, JSON responses use no-store headers, and the
// browser talks to them with plain same-origin fetch.

import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'

const DSH_HOME = process.env.DSH_HOME || path.join(os.homedir(), '.dsh')
const STORE_DIR = path.join(DSH_HOME, 'kidai-clipboard')
const STORE_FILE = path.join(STORE_DIR, 'store.json')

// Body/state size guards: large session snapshots are allowed but bounded.
const MAX_BODY_BYTES = 64 * 1024 * 1024
const MAX_ENTRIES = 5000
const MAX_FOLDERS = 500
const MAX_TAGS = 500
const MAX_SESSION_RECORDS = 8000
const MAX_TEXT_CHARS = 2 * 1024 * 1024
const MAX_TRANSCRIPT_CHARS = 1024 * 1024

const JSON_HEADERS = {
  'Content-Type': 'application/json; charset=utf-8',
  'Access-Control-Allow-Origin': '*',
  'Cache-Control': 'no-store',
}

function emptyState() {
  return {
    schema: 1,
    updatedAt: 0,
    folders: [],
    tags: [],
    entries: [],
    settings: { window: null, ui: {} },
  }
}

function readStore() {
  try {
    const raw = fs.readFileSync(STORE_FILE, 'utf8')
    const value = JSON.parse(raw)
    if (value !== null && typeof value === 'object' && value.schema === 1) return value
  } catch {
    // Missing or malformed store: start empty. Do not crash the plugin over
    // the user's clipboard data; malformed JSON is recoverable manually.
  }
  return emptyState()
}

function writeStore(state) {
  fs.mkdirSync(STORE_DIR, { recursive: true })
  const temporary = `${STORE_FILE}.${process.pid}.tmp`
  try {
    fs.writeFileSync(temporary, JSON.stringify(state, null, 2), 'utf8')
    fs.renameSync(temporary, STORE_FILE)
  } finally {
    try {
      fs.unlinkSync(temporary)
    } catch {}
  }
  return state
}

function isPlainObject(value) {
  return value !== null && typeof value === 'object' && !Array.isArray(value)
}

function boundedString(value, max = MAX_TEXT_CHARS) {
  if (typeof value !== 'string') return null
  return value.length > max ? value.slice(0, max) : value
}

function boundedNumber(value, max) {
  if (typeof value !== 'number' || !Number.isFinite(value)) return null
  return Math.min(value, max)
}

function cleanId(value) {
  if (typeof value !== 'string' || value.length === 0 || value.length > 64) return null
  // UUID-ish ids generated by the client; reject anything path-hostile.
  if (!/^[A-Za-z0-9_-]{1,64}$/.test(value)) return null
  return value
}

function cleanColor(value) {
  if (typeof value !== 'string' || value.length === 0 || value.length > 32) return null
  if (!/^#[0-9a-fA-F]{3,8}$/.test(value) && !value.startsWith('hsl(') && !value.startsWith('var(')) return null
  return value
}

function cleanTimestamp(value) {
  if (typeof value !== 'number' || !Number.isFinite(value)) return null
  return Math.max(0, Math.min(value, Date.now() + 366 * 24 * 3600 * 1000))
}

function sanitizeFolder(raw) {
  if (!isPlainObject(raw)) return null
  const id = cleanId(raw.id)
  if (id === null) return null
  return {
    id,
    name: boundedString(raw.name, 120) ?? '',
    color: cleanColor(raw.color),
    createdAt: cleanTimestamp(raw.createdAt) ?? Date.now(),
  }
}

function sanitizeTag(raw) {
  if (!isPlainObject(raw)) return null
  const id = cleanId(raw.id)
  if (id === null) return null
  return {
    id,
    name: boundedString(raw.name, 80) ?? '',
    color: cleanColor(raw.color),
    createdAt: cleanTimestamp(raw.createdAt) ?? Date.now(),
  }
}

function sanitizeSession(raw) {
  if (!isPlainObject(raw)) return null
  const sessionId = boundedString(raw.sessionId, 128)
  if (sessionId === null) return null
  const records = Array.isArray(raw.records)
    ? raw.records.slice(0, MAX_SESSION_RECORDS)
    : []
  return {
    sessionId,
    capturedAt: cleanTimestamp(raw.capturedAt) ?? Date.now(),
    lastSeq: boundedNumber(raw.lastSeq, Number.MAX_SAFE_INTEGER) ?? 0,
    messageCount: boundedNumber(raw.messageCount, Number.MAX_SAFE_INTEGER) ?? 0,
    chars: boundedNumber(raw.chars, Number.MAX_SAFE_INTEGER) ?? 0,
    title: boundedString(raw.title, 500),
    agentPreset: boundedString(raw.agentPreset, 120),
    cwd: boundedString(raw.cwd, 1024),
    records,
    transcript: boundedString(raw.transcript, MAX_TRANSCRIPT_CHARS),
  }
}

function sanitizeEntry(raw) {
  if (!isPlainObject(raw)) return null
  const id = cleanId(raw.id)
  if (id === null) return null
  const kind = raw.kind === 'session' ? 'session' : raw.kind === 'input' ? 'input' : null
  if (kind === null) return null
  return {
    id,
    kind,
    title: boundedString(raw.title, 300) ?? '',
    text: kind === 'input' ? (boundedString(raw.text) ?? '') : null,
    session: kind === 'session' ? sanitizeSession(raw.session) : null,
    folderId: cleanId(raw.folderId),
    tagIds: Array.isArray(raw.tagIds) ? raw.tagIds.map(cleanId).filter((v) => v !== null).slice(0, 50) : [],
    color: cleanColor(raw.color),
    pinned: raw.pinned === true,
    createdAt: cleanTimestamp(raw.createdAt) ?? Date.now(),
    updatedAt: cleanTimestamp(raw.updatedAt) ?? Date.now(),
  }
}

function sanitizeState(raw) {
  if (!isPlainObject(raw) || raw.schema !== 1) return null
  const folders = Array.isArray(raw.folders)
    ? raw.folders.map(sanitizeFolder).filter((v) => v !== null).slice(0, MAX_FOLDERS)
    : []
  const tags = Array.isArray(raw.tags)
    ? raw.tags.map(sanitizeTag).filter((v) => v !== null).slice(0, MAX_TAGS)
    : []
  const entries = Array.isArray(raw.entries)
    ? raw.entries.map(sanitizeEntry).filter((v) => v !== null).slice(0, MAX_ENTRIES)
    : []
  const folderIds = new Set(folders.map((f) => f.id))
  const tagIds = new Set(tags.map((t) => t.id))
  for (const entry of entries) {
    if (entry.folderId !== null && !folderIds.has(entry.folderId)) entry.folderId = null
    entry.tagIds = entry.tagIds.filter((id) => tagIds.has(id))
  }
  const windowState = isPlainObject(raw.settings?.window)
    ? (() => {
        const width = boundedNumber(raw.settings.window.width, 4096)
        const height = boundedNumber(raw.settings.window.height, 4096)
        const dock = raw.settings.window.dock === 'right' ? 'right' : null
        return {
          x: boundedNumber(raw.settings.window.x, 65536) ?? 0,
          y: boundedNumber(raw.settings.window.y, 65536) ?? 0,
          expanded: raw.settings.window.expanded !== false,
          ...(width !== null ? { width } : {}),
          ...(height !== null ? { height } : {}),
          ...(dock !== null ? { dock } : {}),
        }
      })()
    : null
  return {
    schema: 1,
    updatedAt: cleanTimestamp(raw.updatedAt) ?? Date.now(),
    folders,
    tags,
    entries,
    settings: { window: windowState, ui: isPlainObject(raw.settings?.ui) ? raw.settings.ui : {} },
  }
}

function readBody(req, onDone, onFail) {
  let size = 0
  const chunks = []
  let failed = false
  req.on('data', (chunk) => {
    if (failed) return
    size += chunk.length
    if (size > MAX_BODY_BYTES) {
      failed = true
      try { req.destroy() } catch {}
      onFail(new Error('body too large'))
      return
    }
    chunks.push(chunk)
  })
  req.on('end', () => {
    if (failed) return
    try {
      onDone(Buffer.concat(chunks).toString('utf8'))
    } catch (error) {
      onFail(error)
    }
  })
  req.on('error', onFail)
}

function json(res, code, payload) {
  res.writeHead(code, JSON_HEADERS)
  res.end(JSON.stringify(payload))
}

const STATE_PATH = '/kidai-clipboard/state'

const inject = ['webServer']

/**
 * Register the clipboard storage API. Two verbs, one resource:
 *   GET  /kidai-clipboard/state → { ok, state }
 *   PUT  /kidai-clipboard/state → body { state } → { ok, savedAt }
 * The client is the source of truth for the state shape; the host only
 * sanitizes bounds and persists atomically.
 * @param ctx - Cordis plugin context carrying the webServer service.
 */
function apply(ctx) {
  const disposers = []
  disposers.push(ctx.webServer.register({
    kind: 'exact',
    path: STATE_PATH,
    handler: (req, res) => {
      if (req.method === 'GET') {
        json(res, 200, { ok: true, state: readStore() })
        return
      }
      if (req.method === 'PUT' || req.method === 'POST') {
        readBody(req, (body) => {
          try {
            const parsed = JSON.parse(body)
            const rawState = isPlainObject(parsed) ? parsed.state : null
            if (rawState === null) {
              json(res, 400, { ok: false, error: 'missing state' })
              return
            }
            const state = sanitizeState(rawState)
            if (state === null) {
              json(res, 400, { ok: false, error: 'invalid state (schema must be 1)' })
              return
            }
            writeStore(state)
            json(res, 200, { ok: true, savedAt: Date.now() })
          } catch (error) {
            json(res, 400, { ok: false, error: `bad json: ${String((error && error.message) || error).slice(0, 300)}` })
          }
        }, (error) => {
          json(res, 400, { ok: false, error: String((error && error.message) || error) })
        })
        return
      }
      json(res, 405, { ok: false, error: 'method not allowed' })
    },
  }))

  // Small health route so the client can distinguish "plugin loaded" from
  // "server unreachable" when booting.
  disposers.push(ctx.webServer.register({
    kind: 'exact',
    path: '/kidai-clipboard/ping',
    handler: (req, res) => {
      json(res, 200, { ok: true, stored: fs.existsSync(STORE_FILE) })
    },
  }))

  ctx.effect(() => () => {
    for (const dispose of disposers) {
      try { dispose() } catch {}
    }
  }, 'kidai-clipboard: webserver routes')
}

export { apply, inject }
